on:
  schedule:
    - cron: '58 04 * * Fri'
jobs:
  setup_python:
    name: Setup Python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Create env file
        run: |
          cd data/
          cat << EOF > .env
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_FILE_NAME=${{ secrets.AWS_S3_FILE_NAME }}
          EOF
      - name: Install dependencies
        run: |
          pip install poetry
          cat << EOF > poetry.toml
          [virtualenvs]
          in-project = true
          EOF
          poetry install
      - name: Upload venv folder
        uses: actions/upload-artifact@v2
        with:
          name: venv
          path: .venv/
  
  update-data:
    name: Update Data
    needs: setup_python
    runs-on: ubuntu-latest
    steps: 
      - name: Download venv Folder
        uses: actions/download-artifact@v2
        with:
          name: venv
      - name: Update Data Folder
        run: |
          source $PWD/.venv/bin/activate
          cd data/
          python main.py
      - name: Upload Data
        uses: actions/upload-artifact@v2
        with:
          name: data
          path: data/

  git-push:
    name: Git Push
    needs: update-data
    runs-on: ubuntu-latest
    steps:
      - name: Download Data Folder
        uses: actions/download-artifact@v2
        with:
          name: data
      - name: Git Commit
        run: |
          git config --global user.name 'linooohon'
          git config --global user.email 'linooohon@gmail.com'
          git add .
          git commit -m "[Automated commit] - upate data"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
