on:
  schedule:
    - cron: '20 04 * * Sat'
jobs:
  setup-python-and-update-data:
    name: Setup Python And Update Data
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Create env file
        run: |
          cd data/
          cat << EOF > .env
          AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET=${{ secrets.AWS_S3_BUCKET }}
          AWS_S3_FILE_NAME=${{ secrets.AWS_S3_FILE_NAME }}
          EOF
      - name: Install dependencies
        run: |
          pip install poetry
          cat << EOF > poetry.toml
          [virtualenvs]
          in-project = true
          EOF
          poetry install
      - name: Update Data Folder
        run: |
          source $PWD/.venv/bin/activate
          cd data/
          python main.py
          cd ..
          echo $PWD
      - name: Git Commit
        run: |
          echo $PWD
          git config --global user.name 'linooohon'
          git config --global user.email 'linooohon@gmail.com'
          git add .
          git commit -m "[Automated commit] - upate data"
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
